// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Keep the public experience renderable when a local preview has not been
// configured yet. Production reads the real public Supabase values from
// environment variables; the placeholder is never a credential.
const CLIENT_URL =
  SUPABASE_URL || "https://noble-spaces-preview.invalid";
const CLIENT_KEY = SUPABASE_PUBLISHABLE_KEY || "preview-key-not-configured";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(CLIENT_URL, CLIENT_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});